# Generated by Django 4.0.6 on 2022-08-05 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0019_remove_productreview_author_productreview_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=12)),
                ('street_address', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=6)),
                ('order_quantity', models.PositiveIntegerField(default=1)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
    ]
