# Generated by Django 4.0.6 on 2022-08-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_order_options_productreview_giftproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.order'),
            preserve_default=False,
        ),
    ]
