# Generated by Django 4.0.6 on 2022-07-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_seller_id_methods_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_ID_methods',
            new_name='seller_ID_method',
        ),
    ]
