# Generated by Django 4.0.6 on 2022-07-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_rename_seller_id_methods_seller_seller_id_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-seller_registered_at']},
        ),
    ]
