# Generated by Django 3.2.10 on 2022-07-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_ID_method',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('PAN Card', 'PAN Card')], max_length=20),
        ),
    ]
