# Generated by Django 4.0.6 on 2022-08-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_seller_seller_id_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_ID_method',
            field=models.CharField(choices=[('PAN Card', 'PAN Card'), ('Aadhar Card', 'Aadhar Card')], max_length=20),
        ),
    ]
