# Generated by Django 4.0.6 on 2022-08-05 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0017_alter_seller_seller_id_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='author',
        ),
        migrations.AddField(
            model_name='productreview',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_ID_method',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('PAN Card', 'PAN Card')], max_length=20),
        ),
    ]
