# Generated by Django 4.0.6 on 2022-08-06 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0022_alter_seller_seller_id_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='photo',
            field=models.ImageField(default='xyz.jpeg', upload_to='Customer-Photos', validators=[django.core.validators.validate_image_file_extension]),
            preserve_default=False,
        ),
    ]
