# Generated by Django 3.2.10 on 2022-08-08 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0026_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
